const PostsActionTypes = {
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  POSTS_UPDATE_SUCCESS: "POSTS_UPDATE_SUCCESS",
  POSTS_UPDATE_FAILURE: "POSTS_UPDATE_FAILURE",
};

export default PostsActionTypes;
