const PostsActionTypes = {
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  POST_UPDATE_SUCCESS: "POST_UPDATE_SUCCESS",
  POST_UPDATE_FAILURE: "POST_UPDATE_FAILURE",
  POST_DELETE: "POST_DELETE",
  COMMENT_DELETE: "COMMENT_DELETE",
};

export default PostsActionTypes;
